[package]
name = "Fasching"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.5.0"
sha3 = "0.11.0-pre.3"
bytes = "1.5.0"
